## 数据分片
server:
  servlet:
    context-path: /
  port: 5568

game:
  qs:
    mysql:
      url: xxx.xx.xxx.xxx
      username: xxxxxx
      password: xxxxxx
    signSecret: 123321123     # 接口请求签名秘钥
    jwtSecret: 123321123     # 用于签发jwt的秘钥
    swagger:
      scan: com.game.qs
      hosts: xxx.xx.xxx.xxx:8008,127.0.0.1:5567
      index: 1

logging:
  level:
    root: info
    io:   # 指定包输入日志
      swagger: error
    springfox:
      documentation:
        spring:
          web:
            readers:
              operation: warn
    com:
      game:
        qs: trace

sharding:
  jdbc:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds0
        username: ${game.qs.mysql.username}
        password: ${game.qs.mysql.password}
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds1
        username: ${game.qs.mysql.username}
        password: ${game.qs.mysql.password}
    config:
      sharding:
        binding-tables: t_order,t_order_item
        tables:
          t_order_item:
            table-strategy:
              inline:
                sharding-column: order_id
                algorithm-expression: t_order_item$->{order_id % 2}
            key-generator-column-name: order_item_id
            actual-data-nodes: ds$->{0..1}.t_order_item$->{0..1}
          t_order:
            table-strategy:
              inline:
                sharding-column: order_id
                algorithm-expression: t_order$->{order_id % 2}
            key-generator-column-name: order_id
            actual-data-nodes: ds$->{0..1}.t_order$->{0..1}
        default-database-strategy:
          inline:
            sharding-column: user_id
            algorithm-expression: ds$->{user_id % 2}
        broadcast-tables: t_config
