mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.game.qs.model    # 所有Entity别名类所在包
  mapper-locations:
    - classpath*:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
  profiles:
    active: dev
  application:
    name: sharding-practice-service
  mvc:
    throw-exception-if-no-handler-found: true   #出现错误时, 直接抛出异常
  resources:
    add-mappings: false   #关闭工程中的资源文件建立映射
